apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/instance: argocd
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/environments/dev
    repoURL: https://github.com/fabianmet/argocd-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true