apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sec-guestbook
spec:
  destination:
    namespace: argocd
    name: k3d-secondary
  project: default
  source:
    path: apps/guestbook
    repoURL: https://github.com/fabianmet/argocd-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true